### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by jbonadiman** [tarmac-project/tarmac#88]
Hi! I tried to use Tarmac but had some issues due to the lack of ARM support in the official docker image. I noticed you're already using QEMU and buildx as steps in the pipeline, so I believe just a `platforms: linux/amd64,linux/arm64` in the push-action could add this?

**Comment by madflojo** [comment]
Thanks for opening the issue! I think you are right it’s likely a quick thing to add. I’ll take a crack at it. Appreciate the call out.
